name: test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npx jiti test.ts
        continue-on-error: true
      - run: npx tsx test.ts
        continue-on-error: true
      - run: node --experimental-strip-types test.ts
